### ISSUE TITLE
[iOS]NFC & QRCode打开Clip

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/tap-order#19]
- [x] NFC 启动 TapOrder Clip
- [x] 扫ClipCode  启动 TapOrder Clip
- [x] 扫ClipCode  启动 TapOrder Clip (iOS 15.4以下，通过Settings -> Developer -> Local Experiences (under ‘APP CLIPS TESTING’ section) 测试Pass）

直接扫描或者NFC Tag需要继续观察，AASA有点异常)

**Comment by SuperY** [comment]
合并到 #22
